// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package jupiter

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ExactOutRoute is the `exact_out_route` instruction.
type ExactOutRoute struct {
	RoutePlan      *[]RoutePlanStep
	OutAmount      *uint64
	QuotedInAmount *uint64
	SlippageBps    *uint16
	PlatformFeeBps *uint8

	// [0] = [] token_program
	//
	// [1] = [SIGNER] user_transfer_authority
	//
	// [2] = [WRITE] user_source_token_account
	//
	// [3] = [WRITE] user_destination_token_account
	//
	// [4] = [WRITE] destination_token_account
	//
	// [5] = [] source_mint
	//
	// [6] = [] destination_mint
	//
	// [7] = [WRITE] platform_fee_account
	//
	// [8] = [] token_2022_program
	//
	// [9] = [] event_authority
	//
	// [10] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewExactOutRouteInstructionBuilder creates a new `ExactOutRoute` instruction builder.
func NewExactOutRouteInstructionBuilder() *ExactOutRoute {
	nd := &ExactOutRoute{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	nd.AccountMetaSlice[9] = ag_solanago.Meta(Addresses["D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf"])
	return nd
}

// SetRoutePlan sets the "route_plan" parameter.
func (inst *ExactOutRoute) SetRoutePlan(route_plan []RoutePlanStep) *ExactOutRoute {
	inst.RoutePlan = &route_plan
	return inst
}

// SetOutAmount sets the "out_amount" parameter.
func (inst *ExactOutRoute) SetOutAmount(out_amount uint64) *ExactOutRoute {
	inst.OutAmount = &out_amount
	return inst
}

// SetQuotedInAmount sets the "quoted_in_amount" parameter.
func (inst *ExactOutRoute) SetQuotedInAmount(quoted_in_amount uint64) *ExactOutRoute {
	inst.QuotedInAmount = &quoted_in_amount
	return inst
}

// SetSlippageBps sets the "slippage_bps" parameter.
func (inst *ExactOutRoute) SetSlippageBps(slippage_bps uint16) *ExactOutRoute {
	inst.SlippageBps = &slippage_bps
	return inst
}

// SetPlatformFeeBps sets the "platform_fee_bps" parameter.
func (inst *ExactOutRoute) SetPlatformFeeBps(platform_fee_bps uint8) *ExactOutRoute {
	inst.PlatformFeeBps = &platform_fee_bps
	return inst
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *ExactOutRoute) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *ExactOutRoute) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetUserTransferAuthorityAccount sets the "user_transfer_authority" account.
func (inst *ExactOutRoute) SetUserTransferAuthorityAccount(userTransferAuthority ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(userTransferAuthority).SIGNER()
	return inst
}

// GetUserTransferAuthorityAccount gets the "user_transfer_authority" account.
func (inst *ExactOutRoute) GetUserTransferAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserSourceTokenAccountAccount sets the "user_source_token_account" account.
func (inst *ExactOutRoute) SetUserSourceTokenAccountAccount(userSourceTokenAccount ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(userSourceTokenAccount).WRITE()
	return inst
}

// GetUserSourceTokenAccountAccount gets the "user_source_token_account" account.
func (inst *ExactOutRoute) GetUserSourceTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUserDestinationTokenAccountAccount sets the "user_destination_token_account" account.
func (inst *ExactOutRoute) SetUserDestinationTokenAccountAccount(userDestinationTokenAccount ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(userDestinationTokenAccount).WRITE()
	return inst
}

// GetUserDestinationTokenAccountAccount gets the "user_destination_token_account" account.
func (inst *ExactOutRoute) GetUserDestinationTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetDestinationTokenAccountAccount sets the "destination_token_account" account.
func (inst *ExactOutRoute) SetDestinationTokenAccountAccount(destinationTokenAccount ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(destinationTokenAccount).WRITE()
	return inst
}

// GetDestinationTokenAccountAccount gets the "destination_token_account" account (optional).
func (inst *ExactOutRoute) GetDestinationTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSourceMintAccount sets the "source_mint" account.
func (inst *ExactOutRoute) SetSourceMintAccount(sourceMint ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(sourceMint)
	return inst
}

// GetSourceMintAccount gets the "source_mint" account.
func (inst *ExactOutRoute) GetSourceMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetDestinationMintAccount sets the "destination_mint" account.
func (inst *ExactOutRoute) SetDestinationMintAccount(destinationMint ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(destinationMint)
	return inst
}

// GetDestinationMintAccount gets the "destination_mint" account.
func (inst *ExactOutRoute) GetDestinationMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPlatformFeeAccountAccount sets the "platform_fee_account" account.
func (inst *ExactOutRoute) SetPlatformFeeAccountAccount(platformFeeAccount ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(platformFeeAccount).WRITE()
	return inst
}

// GetPlatformFeeAccountAccount gets the "platform_fee_account" account (optional).
func (inst *ExactOutRoute) GetPlatformFeeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetToken2022ProgramAccount sets the "token_2022_program" account.
func (inst *ExactOutRoute) SetToken2022ProgramAccount(token2022Program ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(token2022Program)
	return inst
}

// GetToken2022ProgramAccount gets the "token_2022_program" account (optional).
func (inst *ExactOutRoute) GetToken2022ProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *ExactOutRoute) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(eventAuthority)
	return inst
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *ExactOutRoute) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetProgramAccount sets the "program" account.
func (inst *ExactOutRoute) SetProgramAccount(program ag_solanago.PublicKey) *ExactOutRoute {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *ExactOutRoute) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst ExactOutRoute) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ExactOutRoute,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ExactOutRoute) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ExactOutRoute) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.RoutePlan == nil {
			return errors.New("RoutePlan parameter is not set")
		}
		if inst.OutAmount == nil {
			return errors.New("OutAmount parameter is not set")
		}
		if inst.QuotedInAmount == nil {
			return errors.New("QuotedInAmount parameter is not set")
		}
		if inst.SlippageBps == nil {
			return errors.New("SlippageBps parameter is not set")
		}
		if inst.PlatformFeeBps == nil {
			return errors.New("PlatformFeeBps parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.UserTransferAuthority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.UserSourceTokenAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.UserDestinationTokenAccount is not set")
		}

		// [4] = DestinationTokenAccount is optional

		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SourceMint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.DestinationMint is not set")
		}

		// [7] = PlatformFeeAccount is optional

		// [8] = Token2022Program is optional

		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *ExactOutRoute) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ExactOutRoute")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("       RoutePlan", *inst.RoutePlan))
						paramsBranch.Child(ag_format.Param("       OutAmount", *inst.OutAmount))
						paramsBranch.Child(ag_format.Param("  QuotedInAmount", *inst.QuotedInAmount))
						paramsBranch.Child(ag_format.Param("     SlippageBps", *inst.SlippageBps))
						paramsBranch.Child(ag_format.Param("  PlatformFeeBps", *inst.PlatformFeeBps))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          token_program", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("user_transfer_authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     user_source_token_", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("user_destination_token_", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("     destination_token_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("            source_mint", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("       destination_mint", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          platform_fee_", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("     token_2022_program", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        event_authority", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("                program", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj ExactOutRoute) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `RoutePlan` param:
	err = encoder.Encode(obj.RoutePlan)
	if err != nil {
		return err
	}
	// Serialize `OutAmount` param:
	err = encoder.Encode(obj.OutAmount)
	if err != nil {
		return err
	}
	// Serialize `QuotedInAmount` param:
	err = encoder.Encode(obj.QuotedInAmount)
	if err != nil {
		return err
	}
	// Serialize `SlippageBps` param:
	err = encoder.Encode(obj.SlippageBps)
	if err != nil {
		return err
	}
	// Serialize `PlatformFeeBps` param:
	err = encoder.Encode(obj.PlatformFeeBps)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ExactOutRoute) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `RoutePlan`:
	err = decoder.Decode(&obj.RoutePlan)
	if err != nil {
		return err
	}
	// Deserialize `OutAmount`:
	err = decoder.Decode(&obj.OutAmount)
	if err != nil {
		return err
	}
	// Deserialize `QuotedInAmount`:
	err = decoder.Decode(&obj.QuotedInAmount)
	if err != nil {
		return err
	}
	// Deserialize `SlippageBps`:
	err = decoder.Decode(&obj.SlippageBps)
	if err != nil {
		return err
	}
	// Deserialize `PlatformFeeBps`:
	err = decoder.Decode(&obj.PlatformFeeBps)
	if err != nil {
		return err
	}
	return nil
}

// NewExactOutRouteInstruction declares a new ExactOutRoute instruction with the provided parameters and accounts.
func NewExactOutRouteInstruction(
	// Parameters:
	route_plan []RoutePlanStep,
	out_amount uint64,
	quoted_in_amount uint64,
	slippage_bps uint16,
	platform_fee_bps uint8,
	// Accounts:
	tokenProgram ag_solanago.PublicKey,
	userTransferAuthority ag_solanago.PublicKey,
	userSourceTokenAccount ag_solanago.PublicKey,
	userDestinationTokenAccount ag_solanago.PublicKey,
	destinationTokenAccount ag_solanago.PublicKey,
	sourceMint ag_solanago.PublicKey,
	destinationMint ag_solanago.PublicKey,
	platformFeeAccount ag_solanago.PublicKey,
	token2022Program ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *ExactOutRoute {
	return NewExactOutRouteInstructionBuilder().
		SetRoutePlan(route_plan).
		SetOutAmount(out_amount).
		SetQuotedInAmount(quoted_in_amount).
		SetSlippageBps(slippage_bps).
		SetPlatformFeeBps(platform_fee_bps).
		SetTokenProgramAccount(tokenProgram).
		SetUserTransferAuthorityAccount(userTransferAuthority).
		SetUserSourceTokenAccountAccount(userSourceTokenAccount).
		SetUserDestinationTokenAccountAccount(userDestinationTokenAccount).
		SetDestinationTokenAccountAccount(destinationTokenAccount).
		SetSourceMintAccount(sourceMint).
		SetDestinationMintAccount(destinationMint).
		SetPlatformFeeAccountAccount(platformFeeAccount).
		SetToken2022ProgramAccount(token2022Program).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
