// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpswap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Buy is the `buy` instruction.
type Buy struct {
	BaseAmountOut    *uint64
	MaxQuoteAmountIn *uint64

	// [0] = [WRITE, SIGNER] user
	//
	// [1] = [WRITE] user_base_token_account
	//
	// [2] = [WRITE] user_quote_token_account
	//
	// [3] = [WRITE] pool_base_token_account
	//
	// [4] = [WRITE] pool_quote_token_account
	//
	// [5] = [WRITE] protocol_fee_recipient_token_account
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBuyInstructionBuilder creates a new `Buy` instruction builder.
func NewBuyInstructionBuilder() *Buy {
	nd := &Buy{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetBaseAmountOut sets the "base_amount_out" parameter.
func (inst *Buy) SetBaseAmountOut(base_amount_out uint64) *Buy {
	inst.BaseAmountOut = &base_amount_out
	return inst
}

// SetMaxQuoteAmountIn sets the "max_quote_amount_in" parameter.
func (inst *Buy) SetMaxQuoteAmountIn(max_quote_amount_in uint64) *Buy {
	inst.MaxQuoteAmountIn = &max_quote_amount_in
	return inst
}

// SetUserAccount sets the "user" account.
func (inst *Buy) SetUserAccount(user ag_solanago.PublicKey) *Buy {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *Buy) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetUserBaseTokenAccountAccount sets the "user_base_token_account" account.
func (inst *Buy) SetUserBaseTokenAccountAccount(userBaseTokenAccount ag_solanago.PublicKey) *Buy {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(userBaseTokenAccount).WRITE()
	return inst
}

// GetUserBaseTokenAccountAccount gets the "user_base_token_account" account.
func (inst *Buy) GetUserBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserQuoteTokenAccountAccount sets the "user_quote_token_account" account.
func (inst *Buy) SetUserQuoteTokenAccountAccount(userQuoteTokenAccount ag_solanago.PublicKey) *Buy {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(userQuoteTokenAccount).WRITE()
	return inst
}

// GetUserQuoteTokenAccountAccount gets the "user_quote_token_account" account.
func (inst *Buy) GetUserQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPoolBaseTokenAccountAccount sets the "pool_base_token_account" account.
func (inst *Buy) SetPoolBaseTokenAccountAccount(poolBaseTokenAccount ag_solanago.PublicKey) *Buy {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(poolBaseTokenAccount).WRITE()
	return inst
}

// GetPoolBaseTokenAccountAccount gets the "pool_base_token_account" account.
func (inst *Buy) GetPoolBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPoolQuoteTokenAccountAccount sets the "pool_quote_token_account" account.
func (inst *Buy) SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount ag_solanago.PublicKey) *Buy {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(poolQuoteTokenAccount).WRITE()
	return inst
}

// GetPoolQuoteTokenAccountAccount gets the "pool_quote_token_account" account.
func (inst *Buy) GetPoolQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetProtocolFeeRecipientTokenAccountAccount sets the "protocol_fee_recipient_token_account" account.
func (inst *Buy) SetProtocolFeeRecipientTokenAccountAccount(protocolFeeRecipientTokenAccount ag_solanago.PublicKey) *Buy {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(protocolFeeRecipientTokenAccount).WRITE()
	return inst
}

// GetProtocolFeeRecipientTokenAccountAccount gets the "protocol_fee_recipient_token_account" account.
func (inst *Buy) GetProtocolFeeRecipientTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst Buy) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Buy,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Buy) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Buy) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BaseAmountOut == nil {
			return errors.New("BaseAmountOut parameter is not set")
		}
		if inst.MaxQuoteAmountIn == nil {
			return errors.New("MaxQuoteAmountIn parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.UserBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.UserQuoteTokenAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.PoolBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.PoolQuoteTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.ProtocolFeeRecipientTokenAccount is not set")
		}
	}
	return nil
}

func (inst *Buy) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Buy")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("      BaseAmountOut", *inst.BaseAmountOut))
						paramsBranch.Child(ag_format.Param("   MaxQuoteAmountIn", *inst.MaxQuoteAmountIn))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                         user", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             user_base_token_", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            user_quote_token_", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("             pool_base_token_", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("            pool_quote_token_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("protocol_fee_recipient_token_", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj Buy) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BaseAmountOut` param:
	err = encoder.Encode(obj.BaseAmountOut)
	if err != nil {
		return err
	}
	// Serialize `MaxQuoteAmountIn` param:
	err = encoder.Encode(obj.MaxQuoteAmountIn)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Buy) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BaseAmountOut`:
	err = decoder.Decode(&obj.BaseAmountOut)
	if err != nil {
		return err
	}
	// Deserialize `MaxQuoteAmountIn`:
	err = decoder.Decode(&obj.MaxQuoteAmountIn)
	if err != nil {
		return err
	}
	return nil
}

// NewBuyInstruction declares a new Buy instruction with the provided parameters and accounts.
func NewBuyInstruction(
	// Parameters:
	base_amount_out uint64,
	max_quote_amount_in uint64,
	// Accounts:
	user ag_solanago.PublicKey,
	userBaseTokenAccount ag_solanago.PublicKey,
	userQuoteTokenAccount ag_solanago.PublicKey,
	poolBaseTokenAccount ag_solanago.PublicKey,
	poolQuoteTokenAccount ag_solanago.PublicKey,
	protocolFeeRecipientTokenAccount ag_solanago.PublicKey) *Buy {
	return NewBuyInstructionBuilder().
		SetBaseAmountOut(base_amount_out).
		SetMaxQuoteAmountIn(max_quote_amount_in).
		SetUserAccount(user).
		SetUserBaseTokenAccountAccount(userBaseTokenAccount).
		SetUserQuoteTokenAccountAccount(userQuoteTokenAccount).
		SetPoolBaseTokenAccountAccount(poolBaseTokenAccount).
		SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount).
		SetProtocolFeeRecipientTokenAccountAccount(protocolFeeRecipientTokenAccount)
}
