// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpswap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Deposit is the `deposit` instruction.
type Deposit struct {
	LpTokenAmountOut *uint64
	MaxBaseAmountIn  *uint64
	MaxQuoteAmountIn *uint64

	// [0] = [WRITE] pool
	//
	// [1] = [WRITE] lp_mint
	//
	// [2] = [WRITE] user_base_token_account
	//
	// [3] = [WRITE] user_quote_token_account
	//
	// [4] = [WRITE] user_pool_token_account
	//
	// [5] = [WRITE] pool_base_token_account
	//
	// [6] = [WRITE] pool_quote_token_account
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDepositInstructionBuilder creates a new `Deposit` instruction builder.
func NewDepositInstructionBuilder() *Deposit {
	nd := &Deposit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetLpTokenAmountOut sets the "lp_token_amount_out" parameter.
func (inst *Deposit) SetLpTokenAmountOut(lp_token_amount_out uint64) *Deposit {
	inst.LpTokenAmountOut = &lp_token_amount_out
	return inst
}

// SetMaxBaseAmountIn sets the "max_base_amount_in" parameter.
func (inst *Deposit) SetMaxBaseAmountIn(max_base_amount_in uint64) *Deposit {
	inst.MaxBaseAmountIn = &max_base_amount_in
	return inst
}

// SetMaxQuoteAmountIn sets the "max_quote_amount_in" parameter.
func (inst *Deposit) SetMaxQuoteAmountIn(max_quote_amount_in uint64) *Deposit {
	inst.MaxQuoteAmountIn = &max_quote_amount_in
	return inst
}

// SetPoolAccount sets the "pool" account.
func (inst *Deposit) SetPoolAccount(pool ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(pool).WRITE()
	return inst
}

// GetPoolAccount gets the "pool" account.
func (inst *Deposit) GetPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetLpMintAccount sets the "lp_mint" account.
func (inst *Deposit) SetLpMintAccount(lpMint ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(lpMint).WRITE()
	return inst
}

// GetLpMintAccount gets the "lp_mint" account.
func (inst *Deposit) GetLpMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserBaseTokenAccountAccount sets the "user_base_token_account" account.
func (inst *Deposit) SetUserBaseTokenAccountAccount(userBaseTokenAccount ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(userBaseTokenAccount).WRITE()
	return inst
}

// GetUserBaseTokenAccountAccount gets the "user_base_token_account" account.
func (inst *Deposit) GetUserBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUserQuoteTokenAccountAccount sets the "user_quote_token_account" account.
func (inst *Deposit) SetUserQuoteTokenAccountAccount(userQuoteTokenAccount ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(userQuoteTokenAccount).WRITE()
	return inst
}

// GetUserQuoteTokenAccountAccount gets the "user_quote_token_account" account.
func (inst *Deposit) GetUserQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserPoolTokenAccountAccount sets the "user_pool_token_account" account.
func (inst *Deposit) SetUserPoolTokenAccountAccount(userPoolTokenAccount ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(userPoolTokenAccount).WRITE()
	return inst
}

// GetUserPoolTokenAccountAccount gets the "user_pool_token_account" account.
func (inst *Deposit) GetUserPoolTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPoolBaseTokenAccountAccount sets the "pool_base_token_account" account.
func (inst *Deposit) SetPoolBaseTokenAccountAccount(poolBaseTokenAccount ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(poolBaseTokenAccount).WRITE()
	return inst
}

// GetPoolBaseTokenAccountAccount gets the "pool_base_token_account" account.
func (inst *Deposit) GetPoolBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetPoolQuoteTokenAccountAccount sets the "pool_quote_token_account" account.
func (inst *Deposit) SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(poolQuoteTokenAccount).WRITE()
	return inst
}

// GetPoolQuoteTokenAccountAccount gets the "pool_quote_token_account" account.
func (inst *Deposit) GetPoolQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst Deposit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Deposit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Deposit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Deposit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.LpTokenAmountOut == nil {
			return errors.New("LpTokenAmountOut parameter is not set")
		}
		if inst.MaxBaseAmountIn == nil {
			return errors.New("MaxBaseAmountIn parameter is not set")
		}
		if inst.MaxQuoteAmountIn == nil {
			return errors.New("MaxQuoteAmountIn parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Pool is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.LpMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.UserBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.UserQuoteTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UserPoolTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.PoolBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.PoolQuoteTokenAccount is not set")
		}
	}
	return nil
}

func (inst *Deposit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Deposit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   LpTokenAmountOut", *inst.LpTokenAmountOut))
						paramsBranch.Child(ag_format.Param("    MaxBaseAmountIn", *inst.MaxBaseAmountIn))
						paramsBranch.Child(ag_format.Param("   MaxQuoteAmountIn", *inst.MaxQuoteAmountIn))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             pool", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          lp_mint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" user_base_token_", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("user_quote_token_", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" user_pool_token_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta(" pool_base_token_", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("pool_quote_token_", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj Deposit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `LpTokenAmountOut` param:
	err = encoder.Encode(obj.LpTokenAmountOut)
	if err != nil {
		return err
	}
	// Serialize `MaxBaseAmountIn` param:
	err = encoder.Encode(obj.MaxBaseAmountIn)
	if err != nil {
		return err
	}
	// Serialize `MaxQuoteAmountIn` param:
	err = encoder.Encode(obj.MaxQuoteAmountIn)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Deposit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `LpTokenAmountOut`:
	err = decoder.Decode(&obj.LpTokenAmountOut)
	if err != nil {
		return err
	}
	// Deserialize `MaxBaseAmountIn`:
	err = decoder.Decode(&obj.MaxBaseAmountIn)
	if err != nil {
		return err
	}
	// Deserialize `MaxQuoteAmountIn`:
	err = decoder.Decode(&obj.MaxQuoteAmountIn)
	if err != nil {
		return err
	}
	return nil
}

// NewDepositInstruction declares a new Deposit instruction with the provided parameters and accounts.
func NewDepositInstruction(
	// Parameters:
	lp_token_amount_out uint64,
	max_base_amount_in uint64,
	max_quote_amount_in uint64,
	// Accounts:
	pool ag_solanago.PublicKey,
	lpMint ag_solanago.PublicKey,
	userBaseTokenAccount ag_solanago.PublicKey,
	userQuoteTokenAccount ag_solanago.PublicKey,
	userPoolTokenAccount ag_solanago.PublicKey,
	poolBaseTokenAccount ag_solanago.PublicKey,
	poolQuoteTokenAccount ag_solanago.PublicKey) *Deposit {
	return NewDepositInstructionBuilder().
		SetLpTokenAmountOut(lp_token_amount_out).
		SetMaxBaseAmountIn(max_base_amount_in).
		SetMaxQuoteAmountIn(max_quote_amount_in).
		SetPoolAccount(pool).
		SetLpMintAccount(lpMint).
		SetUserBaseTokenAccountAccount(userBaseTokenAccount).
		SetUserQuoteTokenAccountAccount(userQuoteTokenAccount).
		SetUserPoolTokenAccountAccount(userPoolTokenAccount).
		SetPoolBaseTokenAccountAccount(poolBaseTokenAccount).
		SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount)
}
