// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpswap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateAdmin is the `update_admin` instruction.
type UpdateAdmin struct {

	// [0] = [WRITE] global_config
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateAdminInstructionBuilder creates a new `UpdateAdmin` instruction builder.
func NewUpdateAdminInstructionBuilder() *UpdateAdmin {
	nd := &UpdateAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 1),
	}
	return nd
}

// SetGlobalConfigAccount sets the "global_config" account.
func (inst *UpdateAdmin) SetGlobalConfigAccount(globalConfig ag_solanago.PublicKey) *UpdateAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(globalConfig).WRITE()
	return inst
}

// GetGlobalConfigAccount gets the "global_config" account.
func (inst *UpdateAdmin) GetGlobalConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst UpdateAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateAdmin) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.GlobalConfig is not set")
		}
	}
	return nil
}

func (inst *UpdateAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=1]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("global_config", inst.AccountMetaSlice.Get(0)))
					})
				})
		})
}

func (obj UpdateAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *UpdateAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewUpdateAdminInstruction declares a new UpdateAdmin instruction with the provided parameters and accounts.
func NewUpdateAdminInstruction(
	// Accounts:
	globalConfig ag_solanago.PublicKey) *UpdateAdmin {
	return NewUpdateAdminInstructionBuilder().
		SetGlobalConfigAccount(globalConfig)
}
