// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpswap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Withdraw is the `withdraw` instruction.
type Withdraw struct {
	LpTokenAmountIn   *uint64
	MinBaseAmountOut  *uint64
	MinQuoteAmountOut *uint64

	// [0] = [WRITE] pool
	//
	// [1] = [WRITE] lp_mint
	//
	// [2] = [WRITE] user_base_token_account
	//
	// [3] = [WRITE] user_quote_token_account
	//
	// [4] = [WRITE] user_pool_token_account
	//
	// [5] = [WRITE] pool_base_token_account
	//
	// [6] = [WRITE] pool_quote_token_account
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawInstructionBuilder creates a new `Withdraw` instruction builder.
func NewWithdrawInstructionBuilder() *Withdraw {
	nd := &Withdraw{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetLpTokenAmountIn sets the "lp_token_amount_in" parameter.
func (inst *Withdraw) SetLpTokenAmountIn(lp_token_amount_in uint64) *Withdraw {
	inst.LpTokenAmountIn = &lp_token_amount_in
	return inst
}

// SetMinBaseAmountOut sets the "min_base_amount_out" parameter.
func (inst *Withdraw) SetMinBaseAmountOut(min_base_amount_out uint64) *Withdraw {
	inst.MinBaseAmountOut = &min_base_amount_out
	return inst
}

// SetMinQuoteAmountOut sets the "min_quote_amount_out" parameter.
func (inst *Withdraw) SetMinQuoteAmountOut(min_quote_amount_out uint64) *Withdraw {
	inst.MinQuoteAmountOut = &min_quote_amount_out
	return inst
}

// SetPoolAccount sets the "pool" account.
func (inst *Withdraw) SetPoolAccount(pool ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(pool).WRITE()
	return inst
}

// GetPoolAccount gets the "pool" account.
func (inst *Withdraw) GetPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetLpMintAccount sets the "lp_mint" account.
func (inst *Withdraw) SetLpMintAccount(lpMint ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(lpMint).WRITE()
	return inst
}

// GetLpMintAccount gets the "lp_mint" account.
func (inst *Withdraw) GetLpMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserBaseTokenAccountAccount sets the "user_base_token_account" account.
func (inst *Withdraw) SetUserBaseTokenAccountAccount(userBaseTokenAccount ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(userBaseTokenAccount).WRITE()
	return inst
}

// GetUserBaseTokenAccountAccount gets the "user_base_token_account" account.
func (inst *Withdraw) GetUserBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUserQuoteTokenAccountAccount sets the "user_quote_token_account" account.
func (inst *Withdraw) SetUserQuoteTokenAccountAccount(userQuoteTokenAccount ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(userQuoteTokenAccount).WRITE()
	return inst
}

// GetUserQuoteTokenAccountAccount gets the "user_quote_token_account" account.
func (inst *Withdraw) GetUserQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserPoolTokenAccountAccount sets the "user_pool_token_account" account.
func (inst *Withdraw) SetUserPoolTokenAccountAccount(userPoolTokenAccount ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(userPoolTokenAccount).WRITE()
	return inst
}

// GetUserPoolTokenAccountAccount gets the "user_pool_token_account" account.
func (inst *Withdraw) GetUserPoolTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPoolBaseTokenAccountAccount sets the "pool_base_token_account" account.
func (inst *Withdraw) SetPoolBaseTokenAccountAccount(poolBaseTokenAccount ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(poolBaseTokenAccount).WRITE()
	return inst
}

// GetPoolBaseTokenAccountAccount gets the "pool_base_token_account" account.
func (inst *Withdraw) GetPoolBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetPoolQuoteTokenAccountAccount sets the "pool_quote_token_account" account.
func (inst *Withdraw) SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(poolQuoteTokenAccount).WRITE()
	return inst
}

// GetPoolQuoteTokenAccountAccount gets the "pool_quote_token_account" account.
func (inst *Withdraw) GetPoolQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst Withdraw) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Withdraw,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Withdraw) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Withdraw) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.LpTokenAmountIn == nil {
			return errors.New("LpTokenAmountIn parameter is not set")
		}
		if inst.MinBaseAmountOut == nil {
			return errors.New("MinBaseAmountOut parameter is not set")
		}
		if inst.MinQuoteAmountOut == nil {
			return errors.New("MinQuoteAmountOut parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Pool is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.LpMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.UserBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.UserQuoteTokenAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UserPoolTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.PoolBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.PoolQuoteTokenAccount is not set")
		}
	}
	return nil
}

func (inst *Withdraw) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Withdraw")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("     LpTokenAmountIn", *inst.LpTokenAmountIn))
						paramsBranch.Child(ag_format.Param("    MinBaseAmountOut", *inst.MinBaseAmountOut))
						paramsBranch.Child(ag_format.Param("   MinQuoteAmountOut", *inst.MinQuoteAmountOut))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             pool", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          lp_mint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" user_base_token_", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("user_quote_token_", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" user_pool_token_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta(" pool_base_token_", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("pool_quote_token_", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj Withdraw) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `LpTokenAmountIn` param:
	err = encoder.Encode(obj.LpTokenAmountIn)
	if err != nil {
		return err
	}
	// Serialize `MinBaseAmountOut` param:
	err = encoder.Encode(obj.MinBaseAmountOut)
	if err != nil {
		return err
	}
	// Serialize `MinQuoteAmountOut` param:
	err = encoder.Encode(obj.MinQuoteAmountOut)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Withdraw) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `LpTokenAmountIn`:
	err = decoder.Decode(&obj.LpTokenAmountIn)
	if err != nil {
		return err
	}
	// Deserialize `MinBaseAmountOut`:
	err = decoder.Decode(&obj.MinBaseAmountOut)
	if err != nil {
		return err
	}
	// Deserialize `MinQuoteAmountOut`:
	err = decoder.Decode(&obj.MinQuoteAmountOut)
	if err != nil {
		return err
	}
	return nil
}

// NewWithdrawInstruction declares a new Withdraw instruction with the provided parameters and accounts.
func NewWithdrawInstruction(
	// Parameters:
	lp_token_amount_in uint64,
	min_base_amount_out uint64,
	min_quote_amount_out uint64,
	// Accounts:
	pool ag_solanago.PublicKey,
	lpMint ag_solanago.PublicKey,
	userBaseTokenAccount ag_solanago.PublicKey,
	userQuoteTokenAccount ag_solanago.PublicKey,
	userPoolTokenAccount ag_solanago.PublicKey,
	poolBaseTokenAccount ag_solanago.PublicKey,
	poolQuoteTokenAccount ag_solanago.PublicKey) *Withdraw {
	return NewWithdrawInstructionBuilder().
		SetLpTokenAmountIn(lp_token_amount_in).
		SetMinBaseAmountOut(min_base_amount_out).
		SetMinQuoteAmountOut(min_quote_amount_out).
		SetPoolAccount(pool).
		SetLpMintAccount(lpMint).
		SetUserBaseTokenAccountAccount(userBaseTokenAccount).
		SetUserQuoteTokenAccountAccount(userQuoteTokenAccount).
		SetUserPoolTokenAccountAccount(userPoolTokenAccount).
		SetPoolBaseTokenAccountAccount(poolBaseTokenAccount).
		SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount)
}
