// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package solfi

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateOracles is the `updateOracles` instruction.
type UpdateOracles struct {

	// [0] = [WRITE] tradingPair
	//
	// [1] = [] mintX
	//
	// [2] = [] mintY
	//
	// [3] = [] xPriceFeed
	//
	// [4] = [] yPriceFeed
	//
	// [5] = [SIGNER] user
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateOraclesInstructionBuilder creates a new `UpdateOracles` instruction builder.
func NewUpdateOraclesInstructionBuilder() *UpdateOracles {
	nd := &UpdateOracles{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetTradingPairAccount sets the "tradingPair" account.
func (inst *UpdateOracles) SetTradingPairAccount(tradingPair ag_solanago.PublicKey) *UpdateOracles {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tradingPair).WRITE()
	return inst
}

// GetTradingPairAccount gets the "tradingPair" account.
func (inst *UpdateOracles) GetTradingPairAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMintXAccount sets the "mintX" account.
func (inst *UpdateOracles) SetMintXAccount(mintX ag_solanago.PublicKey) *UpdateOracles {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(mintX)
	return inst
}

// GetMintXAccount gets the "mintX" account.
func (inst *UpdateOracles) GetMintXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintYAccount sets the "mintY" account.
func (inst *UpdateOracles) SetMintYAccount(mintY ag_solanago.PublicKey) *UpdateOracles {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mintY)
	return inst
}

// GetMintYAccount gets the "mintY" account.
func (inst *UpdateOracles) GetMintYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetXPriceFeedAccount sets the "xPriceFeed" account.
func (inst *UpdateOracles) SetXPriceFeedAccount(xPriceFeed ag_solanago.PublicKey) *UpdateOracles {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(xPriceFeed)
	return inst
}

// GetXPriceFeedAccount gets the "xPriceFeed" account.
func (inst *UpdateOracles) GetXPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetYPriceFeedAccount sets the "yPriceFeed" account.
func (inst *UpdateOracles) SetYPriceFeedAccount(yPriceFeed ag_solanago.PublicKey) *UpdateOracles {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(yPriceFeed)
	return inst
}

// GetYPriceFeedAccount gets the "yPriceFeed" account.
func (inst *UpdateOracles) GetYPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserAccount sets the "user" account.
func (inst *UpdateOracles) SetUserAccount(user ag_solanago.PublicKey) *UpdateOracles {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(user).SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *UpdateOracles) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst UpdateOracles) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.TypeIDFromUint8(Instruction_UpdateOracles),
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateOracles) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateOracles) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TradingPair is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MintX is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.MintY is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.XPriceFeed is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.YPriceFeed is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.User is not set")
		}
	}
	return nil
}

func (inst *UpdateOracles) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateOracles")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("tradingPair", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      mintX", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      mintY", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" xPriceFeed", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" yPriceFeed", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       user", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj UpdateOracles) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *UpdateOracles) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewUpdateOraclesInstruction declares a new UpdateOracles instruction with the provided parameters and accounts.
func NewUpdateOraclesInstruction(
	// Accounts:
	tradingPair ag_solanago.PublicKey,
	mintX ag_solanago.PublicKey,
	mintY ag_solanago.PublicKey,
	xPriceFeed ag_solanago.PublicKey,
	yPriceFeed ag_solanago.PublicKey,
	user ag_solanago.PublicKey) *UpdateOracles {
	return NewUpdateOraclesInstructionBuilder().
		SetTradingPairAccount(tradingPair).
		SetMintXAccount(mintX).
		SetMintYAccount(mintY).
		SetXPriceFeedAccount(xPriceFeed).
		SetYPriceFeedAccount(yPriceFeed).
		SetUserAccount(user)
}
