// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package obric_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Deposit is the `deposit` instruction.
type Deposit struct {
	InputX *uint64
	InputY *uint64

	// [0] = [WRITE] tradingPair
	//
	// [1] = [] mintX
	//
	// [2] = [] mintY
	//
	// [3] = [WRITE] reserveX
	//
	// [4] = [WRITE] reserveY
	//
	// [5] = [WRITE] userTokenAccountX
	//
	// [6] = [WRITE] userTokenAccountY
	//
	// [7] = [WRITE] mintSslpX
	//
	// [8] = [WRITE] mintSslpY
	//
	// [9] = [WRITE] userSslpX
	//
	// [10] = [WRITE] userSslpY
	//
	// [11] = [] xPriceFeed
	//
	// [12] = [] yPriceFeed
	//
	// [13] = [WRITE, SIGNER] user
	//
	// [14] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDepositInstructionBuilder creates a new `Deposit` instruction builder.
func NewDepositInstructionBuilder() *Deposit {
	nd := &Deposit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 15),
	}
	return nd
}

// SetInputX sets the "inputX" parameter.
func (inst *Deposit) SetInputX(inputX uint64) *Deposit {
	inst.InputX = &inputX
	return inst
}

// SetInputY sets the "inputY" parameter.
func (inst *Deposit) SetInputY(inputY uint64) *Deposit {
	inst.InputY = &inputY
	return inst
}

// SetTradingPairAccount sets the "tradingPair" account.
func (inst *Deposit) SetTradingPairAccount(tradingPair ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tradingPair).WRITE()
	return inst
}

// GetTradingPairAccount gets the "tradingPair" account.
func (inst *Deposit) GetTradingPairAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMintXAccount sets the "mintX" account.
func (inst *Deposit) SetMintXAccount(mintX ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(mintX)
	return inst
}

// GetMintXAccount gets the "mintX" account.
func (inst *Deposit) GetMintXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintYAccount sets the "mintY" account.
func (inst *Deposit) SetMintYAccount(mintY ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mintY)
	return inst
}

// GetMintYAccount gets the "mintY" account.
func (inst *Deposit) GetMintYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetReserveXAccount sets the "reserveX" account.
func (inst *Deposit) SetReserveXAccount(reserveX ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(reserveX).WRITE()
	return inst
}

// GetReserveXAccount gets the "reserveX" account.
func (inst *Deposit) GetReserveXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetReserveYAccount sets the "reserveY" account.
func (inst *Deposit) SetReserveYAccount(reserveY ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(reserveY).WRITE()
	return inst
}

// GetReserveYAccount gets the "reserveY" account.
func (inst *Deposit) GetReserveYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserTokenAccountXAccount sets the "userTokenAccountX" account.
func (inst *Deposit) SetUserTokenAccountXAccount(userTokenAccountX ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userTokenAccountX).WRITE()
	return inst
}

// GetUserTokenAccountXAccount gets the "userTokenAccountX" account.
func (inst *Deposit) GetUserTokenAccountXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetUserTokenAccountYAccount sets the "userTokenAccountY" account.
func (inst *Deposit) SetUserTokenAccountYAccount(userTokenAccountY ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(userTokenAccountY).WRITE()
	return inst
}

// GetUserTokenAccountYAccount gets the "userTokenAccountY" account.
func (inst *Deposit) GetUserTokenAccountYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMintSslpXAccount sets the "mintSslpX" account.
func (inst *Deposit) SetMintSslpXAccount(mintSslpX ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(mintSslpX).WRITE()
	return inst
}

// GetMintSslpXAccount gets the "mintSslpX" account.
func (inst *Deposit) GetMintSslpXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetMintSslpYAccount sets the "mintSslpY" account.
func (inst *Deposit) SetMintSslpYAccount(mintSslpY ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(mintSslpY).WRITE()
	return inst
}

// GetMintSslpYAccount gets the "mintSslpY" account.
func (inst *Deposit) GetMintSslpYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetUserSslpXAccount sets the "userSslpX" account.
func (inst *Deposit) SetUserSslpXAccount(userSslpX ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(userSslpX).WRITE()
	return inst
}

// GetUserSslpXAccount gets the "userSslpX" account.
func (inst *Deposit) GetUserSslpXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetUserSslpYAccount sets the "userSslpY" account.
func (inst *Deposit) SetUserSslpYAccount(userSslpY ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(userSslpY).WRITE()
	return inst
}

// GetUserSslpYAccount gets the "userSslpY" account.
func (inst *Deposit) GetUserSslpYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetXPriceFeedAccount sets the "xPriceFeed" account.
func (inst *Deposit) SetXPriceFeedAccount(xPriceFeed ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(xPriceFeed)
	return inst
}

// GetXPriceFeedAccount gets the "xPriceFeed" account.
func (inst *Deposit) GetXPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetYPriceFeedAccount sets the "yPriceFeed" account.
func (inst *Deposit) SetYPriceFeedAccount(yPriceFeed ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(yPriceFeed)
	return inst
}

// GetYPriceFeedAccount gets the "yPriceFeed" account.
func (inst *Deposit) GetYPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetUserAccount sets the "user" account.
func (inst *Deposit) SetUserAccount(user ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *Deposit) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Deposit) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Deposit {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Deposit) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

func (inst Deposit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Deposit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Deposit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Deposit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.InputX == nil {
			return errors.New("InputX parameter is not set")
		}
		if inst.InputY == nil {
			return errors.New("InputY parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TradingPair is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MintX is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.MintY is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.ReserveX is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ReserveY is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserTokenAccountX is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.UserTokenAccountY is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.MintSslpX is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.MintSslpY is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.UserSslpX is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.UserSslpY is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.XPriceFeed is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.YPriceFeed is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *Deposit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Deposit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("InputX", *inst.InputX))
						paramsBranch.Child(ag_format.Param("InputY", *inst.InputY))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=15]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      tradingPair", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            mintX", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            mintY", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("         reserveX", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("         reserveY", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("userTokenAccountX", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("userTokenAccountY", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        mintSslpX", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("        mintSslpY", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        userSslpX", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("        userSslpY", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("       xPriceFeed", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("       yPriceFeed", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("             user", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("     tokenProgram", inst.AccountMetaSlice.Get(14)))
					})
				})
		})
}

func (obj Deposit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `InputX` param:
	err = encoder.Encode(obj.InputX)
	if err != nil {
		return err
	}
	// Serialize `InputY` param:
	err = encoder.Encode(obj.InputY)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Deposit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `InputX`:
	err = decoder.Decode(&obj.InputX)
	if err != nil {
		return err
	}
	// Deserialize `InputY`:
	err = decoder.Decode(&obj.InputY)
	if err != nil {
		return err
	}
	return nil
}

// NewDepositInstruction declares a new Deposit instruction with the provided parameters and accounts.
func NewDepositInstruction(
	// Parameters:
	inputX uint64,
	inputY uint64,
	// Accounts:
	tradingPair ag_solanago.PublicKey,
	mintX ag_solanago.PublicKey,
	mintY ag_solanago.PublicKey,
	reserveX ag_solanago.PublicKey,
	reserveY ag_solanago.PublicKey,
	userTokenAccountX ag_solanago.PublicKey,
	userTokenAccountY ag_solanago.PublicKey,
	mintSslpX ag_solanago.PublicKey,
	mintSslpY ag_solanago.PublicKey,
	userSslpX ag_solanago.PublicKey,
	userSslpY ag_solanago.PublicKey,
	xPriceFeed ag_solanago.PublicKey,
	yPriceFeed ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *Deposit {
	return NewDepositInstructionBuilder().
		SetInputX(inputX).
		SetInputY(inputY).
		SetTradingPairAccount(tradingPair).
		SetMintXAccount(mintX).
		SetMintYAccount(mintY).
		SetReserveXAccount(reserveX).
		SetReserveYAccount(reserveY).
		SetUserTokenAccountXAccount(userTokenAccountX).
		SetUserTokenAccountYAccount(userTokenAccountY).
		SetMintSslpXAccount(mintSslpX).
		SetMintSslpYAccount(mintSslpY).
		SetUserSslpXAccount(userSslpX).
		SetUserSslpYAccount(userSslpY).
		SetXPriceFeedAccount(xPriceFeed).
		SetYPriceFeedAccount(yPriceFeed).
		SetUserAccount(user).
		SetTokenProgramAccount(tokenProgram)
}
