// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package obric_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SwapXToY is the `swapXToY` instruction.
type SwapXToY struct {
	InputX       *uint64
	MinOutputAmt *uint64

	// [0] = [WRITE] tradingPair
	//
	// [1] = [] mintX
	//
	// [2] = [] mintY
	//
	// [3] = [WRITE] reserveX
	//
	// [4] = [WRITE] reserveY
	//
	// [5] = [WRITE] userTokenAccountX
	//
	// [6] = [WRITE] userTokenAccountY
	//
	// [7] = [WRITE] protocolFeeY
	//
	// [8] = [] xPriceFeed
	//
	// [9] = [] yPriceFeed
	//
	// [10] = [SIGNER] user
	//
	// [11] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSwapXToYInstructionBuilder creates a new `SwapXToY` instruction builder.
func NewSwapXToYInstructionBuilder() *SwapXToY {
	nd := &SwapXToY{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 12),
	}
	return nd
}

// SetInputX sets the "inputX" parameter.
func (inst *SwapXToY) SetInputX(inputX uint64) *SwapXToY {
	inst.InputX = &inputX
	return inst
}

// SetMinOutputAmt sets the "minOutputAmt" parameter.
func (inst *SwapXToY) SetMinOutputAmt(minOutputAmt uint64) *SwapXToY {
	inst.MinOutputAmt = &minOutputAmt
	return inst
}

// SetTradingPairAccount sets the "tradingPair" account.
func (inst *SwapXToY) SetTradingPairAccount(tradingPair ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tradingPair).WRITE()
	return inst
}

// GetTradingPairAccount gets the "tradingPair" account.
func (inst *SwapXToY) GetTradingPairAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMintXAccount sets the "mintX" account.
func (inst *SwapXToY) SetMintXAccount(mintX ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(mintX)
	return inst
}

// GetMintXAccount gets the "mintX" account.
func (inst *SwapXToY) GetMintXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintYAccount sets the "mintY" account.
func (inst *SwapXToY) SetMintYAccount(mintY ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mintY)
	return inst
}

// GetMintYAccount gets the "mintY" account.
func (inst *SwapXToY) GetMintYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetReserveXAccount sets the "reserveX" account.
func (inst *SwapXToY) SetReserveXAccount(reserveX ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(reserveX).WRITE()
	return inst
}

// GetReserveXAccount gets the "reserveX" account.
func (inst *SwapXToY) GetReserveXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetReserveYAccount sets the "reserveY" account.
func (inst *SwapXToY) SetReserveYAccount(reserveY ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(reserveY).WRITE()
	return inst
}

// GetReserveYAccount gets the "reserveY" account.
func (inst *SwapXToY) GetReserveYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserTokenAccountXAccount sets the "userTokenAccountX" account.
func (inst *SwapXToY) SetUserTokenAccountXAccount(userTokenAccountX ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userTokenAccountX).WRITE()
	return inst
}

// GetUserTokenAccountXAccount gets the "userTokenAccountX" account.
func (inst *SwapXToY) GetUserTokenAccountXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetUserTokenAccountYAccount sets the "userTokenAccountY" account.
func (inst *SwapXToY) SetUserTokenAccountYAccount(userTokenAccountY ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(userTokenAccountY).WRITE()
	return inst
}

// GetUserTokenAccountYAccount gets the "userTokenAccountY" account.
func (inst *SwapXToY) GetUserTokenAccountYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetProtocolFeeYAccount sets the "protocolFeeY" account.
func (inst *SwapXToY) SetProtocolFeeYAccount(protocolFeeY ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(protocolFeeY).WRITE()
	return inst
}

// GetProtocolFeeYAccount gets the "protocolFeeY" account.
func (inst *SwapXToY) GetProtocolFeeYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetXPriceFeedAccount sets the "xPriceFeed" account.
func (inst *SwapXToY) SetXPriceFeedAccount(xPriceFeed ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(xPriceFeed)
	return inst
}

// GetXPriceFeedAccount gets the "xPriceFeed" account.
func (inst *SwapXToY) GetXPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetYPriceFeedAccount sets the "yPriceFeed" account.
func (inst *SwapXToY) SetYPriceFeedAccount(yPriceFeed ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(yPriceFeed)
	return inst
}

// GetYPriceFeedAccount gets the "yPriceFeed" account.
func (inst *SwapXToY) GetYPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetUserAccount sets the "user" account.
func (inst *SwapXToY) SetUserAccount(user ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(user).SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *SwapXToY) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *SwapXToY) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *SwapXToY {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *SwapXToY) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

func (inst SwapXToY) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SwapXToY,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SwapXToY) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SwapXToY) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.InputX == nil {
			return errors.New("InputX parameter is not set")
		}
		if inst.MinOutputAmt == nil {
			return errors.New("MinOutputAmt parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TradingPair is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MintX is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.MintY is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.ReserveX is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ReserveY is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserTokenAccountX is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.UserTokenAccountY is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.ProtocolFeeY is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.XPriceFeed is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.YPriceFeed is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *SwapXToY) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SwapXToY")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("      InputX", *inst.InputX))
						paramsBranch.Child(ag_format.Param("MinOutputAmt", *inst.MinOutputAmt))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=12]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      tradingPair", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            mintX", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            mintY", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("         reserveX", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("         reserveY", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("userTokenAccountX", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("userTokenAccountY", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("     protocolFeeY", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("       xPriceFeed", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("       yPriceFeed", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("             user", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("     tokenProgram", inst.AccountMetaSlice.Get(11)))
					})
				})
		})
}

func (obj SwapXToY) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `InputX` param:
	err = encoder.Encode(obj.InputX)
	if err != nil {
		return err
	}
	// Serialize `MinOutputAmt` param:
	err = encoder.Encode(obj.MinOutputAmt)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SwapXToY) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `InputX`:
	err = decoder.Decode(&obj.InputX)
	if err != nil {
		return err
	}
	// Deserialize `MinOutputAmt`:
	err = decoder.Decode(&obj.MinOutputAmt)
	if err != nil {
		return err
	}
	return nil
}

// NewSwapXToYInstruction declares a new SwapXToY instruction with the provided parameters and accounts.
func NewSwapXToYInstruction(
	// Parameters:
	inputX uint64,
	minOutputAmt uint64,
	// Accounts:
	tradingPair ag_solanago.PublicKey,
	mintX ag_solanago.PublicKey,
	mintY ag_solanago.PublicKey,
	reserveX ag_solanago.PublicKey,
	reserveY ag_solanago.PublicKey,
	userTokenAccountX ag_solanago.PublicKey,
	userTokenAccountY ag_solanago.PublicKey,
	protocolFeeY ag_solanago.PublicKey,
	xPriceFeed ag_solanago.PublicKey,
	yPriceFeed ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *SwapXToY {
	return NewSwapXToYInstructionBuilder().
		SetInputX(inputX).
		SetMinOutputAmt(minOutputAmt).
		SetTradingPairAccount(tradingPair).
		SetMintXAccount(mintX).
		SetMintYAccount(mintY).
		SetReserveXAccount(reserveX).
		SetReserveYAccount(reserveY).
		SetUserTokenAccountXAccount(userTokenAccountX).
		SetUserTokenAccountYAccount(userTokenAccountY).
		SetProtocolFeeYAccount(protocolFeeY).
		SetXPriceFeedAccount(xPriceFeed).
		SetYPriceFeedAccount(yPriceFeed).
		SetUserAccount(user).
		SetTokenProgramAccount(tokenProgram)
}
