// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package obric_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateConcentration is the `updateConcentration` instruction.
type UpdateConcentration struct {
	Concentration *uint64

	// [0] = [WRITE] tradingPair
	//
	// [1] = [] mintX
	//
	// [2] = [] mintY
	//
	// [3] = [] xPriceFeed
	//
	// [4] = [] yPriceFeed
	//
	// [5] = [SIGNER] user
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateConcentrationInstructionBuilder creates a new `UpdateConcentration` instruction builder.
func NewUpdateConcentrationInstructionBuilder() *UpdateConcentration {
	nd := &UpdateConcentration{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetConcentration sets the "concentration" parameter.
func (inst *UpdateConcentration) SetConcentration(concentration uint64) *UpdateConcentration {
	inst.Concentration = &concentration
	return inst
}

// SetTradingPairAccount sets the "tradingPair" account.
func (inst *UpdateConcentration) SetTradingPairAccount(tradingPair ag_solanago.PublicKey) *UpdateConcentration {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(tradingPair).WRITE()
	return inst
}

// GetTradingPairAccount gets the "tradingPair" account.
func (inst *UpdateConcentration) GetTradingPairAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMintXAccount sets the "mintX" account.
func (inst *UpdateConcentration) SetMintXAccount(mintX ag_solanago.PublicKey) *UpdateConcentration {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(mintX)
	return inst
}

// GetMintXAccount gets the "mintX" account.
func (inst *UpdateConcentration) GetMintXAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintYAccount sets the "mintY" account.
func (inst *UpdateConcentration) SetMintYAccount(mintY ag_solanago.PublicKey) *UpdateConcentration {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mintY)
	return inst
}

// GetMintYAccount gets the "mintY" account.
func (inst *UpdateConcentration) GetMintYAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetXPriceFeedAccount sets the "xPriceFeed" account.
func (inst *UpdateConcentration) SetXPriceFeedAccount(xPriceFeed ag_solanago.PublicKey) *UpdateConcentration {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(xPriceFeed)
	return inst
}

// GetXPriceFeedAccount gets the "xPriceFeed" account.
func (inst *UpdateConcentration) GetXPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetYPriceFeedAccount sets the "yPriceFeed" account.
func (inst *UpdateConcentration) SetYPriceFeedAccount(yPriceFeed ag_solanago.PublicKey) *UpdateConcentration {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(yPriceFeed)
	return inst
}

// GetYPriceFeedAccount gets the "yPriceFeed" account.
func (inst *UpdateConcentration) GetYPriceFeedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserAccount sets the "user" account.
func (inst *UpdateConcentration) SetUserAccount(user ag_solanago.PublicKey) *UpdateConcentration {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(user).SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *UpdateConcentration) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst UpdateConcentration) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateConcentration,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateConcentration) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateConcentration) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Concentration == nil {
			return errors.New("Concentration parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.TradingPair is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MintX is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.MintY is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.XPriceFeed is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.YPriceFeed is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.User is not set")
		}
	}
	return nil
}

func (inst *UpdateConcentration) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateConcentration")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Concentration", *inst.Concentration))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("tradingPair", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      mintX", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      mintY", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" xPriceFeed", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" yPriceFeed", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       user", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj UpdateConcentration) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Concentration` param:
	err = encoder.Encode(obj.Concentration)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateConcentration) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Concentration`:
	err = decoder.Decode(&obj.Concentration)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateConcentrationInstruction declares a new UpdateConcentration instruction with the provided parameters and accounts.
func NewUpdateConcentrationInstruction(
	// Parameters:
	concentration uint64,
	// Accounts:
	tradingPair ag_solanago.PublicKey,
	mintX ag_solanago.PublicKey,
	mintY ag_solanago.PublicKey,
	xPriceFeed ag_solanago.PublicKey,
	yPriceFeed ag_solanago.PublicKey,
	user ag_solanago.PublicKey) *UpdateConcentration {
	return NewUpdateConcentrationInstructionBuilder().
		SetConcentration(concentration).
		SetTradingPairAccount(tradingPair).
		SetMintXAccount(mintX).
		SetMintYAccount(mintY).
		SetXPriceFeedAccount(xPriceFeed).
		SetYPriceFeedAccount(yPriceFeed).
		SetUserAccount(user)
}
